import ast
import re
import hashlib
import sqlite3
import functools

from aria.rootcause.categories import RootCauseCategory
from aria.gatekeeper.validator import FORBIDDEN_IMPORTS

# --- FEATURE VOCABULARY ---
CANDIDATE_FEATURES = [
    "source_lines_of_code",
    "source_cyclomatic_complexity_est",
    "fix_summary_word_count",
    "has_retry_logic",
    "has_input_validation",
    "has_exception_handling",
    "exception_scope_width",
    "has_timeout_param",
    "has_logging",
    "import_count",
    "has_forbidden_imports",
    "is_malformed",
]

STRATEGY_FEATURES = [
    "strategy_is_rule_guided",
    "strategy_is_retrieval_based",
    "strategy_is_structural",
    "strategy_is_mutation",
    "strategy_is_bred",
]

RULE_FEATURES = [
    "applicable_active_rules_count",
    "rule_compliance_score",
    "top_rule_confidence",
    "any_security_rule_violated",
]

TOOL_HISTORY_FEATURES = [
    "tool_historical_fix_success_rate",
    "tool_active_failure_pattern_count",
    "tool_dominant_root_cause_0",
    "tool_dominant_root_cause_1",
    "tool_dominant_root_cause_2",
    "tool_dominant_root_cause_3",
    "tool_dominant_root_cause_4",
    "tool_dominant_root_cause_5",
    "tool_dominant_root_cause_6",
    "tool_prior_similar_fix_count",
    "tool_population_avg_score",
    "tool_evolution_runs_count",
    "tool_breeding_ever_won",
]

CYCLE_FEATURES = [
    "trigger_is_hypothesis",
    "hypothesis_confidence",
    "failure_pattern_occurrence_count",
    "failure_memory_score",
]

ALL_FEATURES = (CANDIDATE_FEATURES + STRATEGY_FEATURES + RULE_FEATURES
                + TOOL_HISTORY_FEATURES + CYCLE_FEATURES)


# --- HELPERS ---
def _source_complexity(source_code: str) -> dict:
    """
    Parse with ast.parse (safe — no execution). On parse failure (malformed code
    generated by LLM), return sentinel values for all complexity features — this
    itself is a signal (malformed code => likely disqualification => label=0).
    """
    try:
        tree = ast.parse(source_code)
    except SyntaxError:
        return {"lines": -1.0, "complexity": -1.0, "import_count": -1.0, "is_malformed": 1.0}
    lines = len(source_code.splitlines())
    complexity = sum(
        1 for node in ast.walk(tree)
        if isinstance(node, (ast.If, ast.For, ast.While, ast.ExceptHandler,
                              ast.With, ast.Assert))
    )
    imports = sum(1 for node in ast.walk(tree)
                  if isinstance(node, (ast.Import, ast.ImportFrom)))
    return {"lines": float(lines), "complexity": float(complexity),
            "import_count": float(imports), "is_malformed": 0.0}

def _exception_scope_width(source_code: str) -> float:
    """0=no except, 1=specific, 2=broad Exception, 3=bare except"""
    if 'except:' in source_code:        return 3.0
    if 'except Exception' in source_code: return 2.0
    if 'except ' in source_code:        return 1.0
    return 0.0

def _has_forbidden_imports(source_code: str, forbidden: list) -> float:
    """Check against Gatekeeper's forbidden import list."""
    for imp in forbidden:
        if re.search(rf'import\s+{re.escape(imp)}|from\s+{re.escape(imp)}', source_code):
            return 1.0
    return 0.0

def _encode_root_cause(category: str | None) -> list[float]:
    """Returns a 7-element list, one per RootCauseCategory, with a 1.0 at the
    matching index and 0.0 elsewhere. None category -> all zeros (unknown)."""
    ordered = list(RootCauseCategory)
    return [1.0 if (category == c.value) else 0.0 for c in ordered]

@functools.lru_cache(maxsize=128)
def _tool_history_features(tool_name: str, db_path: str) -> dict:
    """
    All queries here MUST use indexed columns (tool_name indexes confirmed from
    Phase 1/4 migrations). Cache results for the duration of one training run
    (LRU cache keyed by tool_name + db_path) — these are called N times per
    dataset build where N = candidates per tool, so caching is important.
    """
    if not tool_name:
        return {}

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    features = {}

    try:
        # tool_historical_fix_success_rate
        rows = cursor.execute("SELECT result FROM improvement_history WHERE tool_name = ?", (tool_name,)).fetchall()
        if rows:
            deployed = sum(1 for r in rows if dict(r).get('result') == 'deployed')
            total = len(rows)
            features["tool_historical_fix_success_rate"] = deployed / total if total > 0 else 0.0
        else:
            features["tool_historical_fix_success_rate"] = 0.0

        # tool_active_failure_pattern_count
        row = cursor.execute("SELECT COUNT(*) as cnt FROM failure_patterns WHERE tool_name = ? AND status = 'active'", (tool_name,)).fetchone()
        features["tool_active_failure_pattern_count"] = float(dict(row).get("cnt", 0)) if row else 0.0

        # tool_prior_similar_fix_count (fallback sentinel if complex signature matching isn't here)
        features["tool_prior_similar_fix_count"] = -1.0

        # tool_population_avg_score
        row = cursor.execute("SELECT AVG(composite_score) as avg_score FROM evolution_population WHERE tool_name = ?", (tool_name,)).fetchone()
        features["tool_population_avg_score"] = float(dict(row).get("avg_score", -1.0)) if row and dict(row).get("avg_score") is not None else -1.0

        # tool_evolution_runs_count
        row = cursor.execute("SELECT COUNT(*) as cnt FROM evolution_runs WHERE tool_name = ?", (tool_name,)).fetchone()
        features["tool_evolution_runs_count"] = float(dict(row).get("cnt", 0)) if row else 0.0

        # tool_breeding_ever_won
        features["tool_breeding_ever_won"] = -1.0 # Requires deeper join with evolution_candidates on 'bred'
        
        # Determine dominant root cause via failure patterns
        rows = cursor.execute("SELECT root_cause_category, COUNT(*) as cnt FROM failure_patterns WHERE tool_name = ? GROUP BY root_cause_category ORDER BY cnt DESC LIMIT 1", (tool_name,)).fetchone()
        if rows:
            category = dict(rows).get("root_cause_category")
        else:
            category = None
            
        rc_encoded = _encode_root_cause(category)
        for i in range(7):
            features[f"tool_dominant_root_cause_{i}"] = rc_encoded[i]

    except sqlite3.OperationalError:
        # Graceful degradation if tables don't exist
        features = {}

    conn.close()
    return features


def compute_feature_vector(
    candidate: dict,
    run_context: dict,
    db_path: str,
) -> tuple[list[float], str]:
    """
    Returns (feature_vector, feature_vector_hash).
    All features are floats (bools become 0.0/1.0, categoricals are one-hot).
    Missing values get a defined sentinel: -1.0 for "unknown/unavailable" fields.
    """
    vec = []
    source_code = candidate.get("source_code", "")
    if source_code is None:
        source_code = ""
    
    # --- CANDIDATE FEATURES ---
    comp = _source_complexity(source_code)
    
    # "source_lines_of_code"
    vec.append(comp["lines"])
    # "source_cyclomatic_complexity_est"
    vec.append(comp["complexity"])
    
    # "fix_summary_word_count"
    fix_summary = candidate.get("fix_summary", "")
    vec.append(float(len(fix_summary.split())) if fix_summary else -1.0)
    
    # "has_retry_logic"
    has_retry = 1.0 if re.search(r'retry|backoff|attempt', source_code, re.IGNORECASE) else 0.0
    vec.append(has_retry)
    
    # "has_input_validation"
    has_valid = 1.0 if re.search(r'isinstance|if not|raise ValueError', source_code) else 0.0
    vec.append(has_valid)
    
    # "has_exception_handling"
    has_except = 1.0 if 'try:' in source_code or 'except' in source_code else 0.0
    vec.append(has_except)
    
    # "exception_scope_width"
    vec.append(_exception_scope_width(source_code))
    
    # "has_timeout_param"
    has_timeout = 1.0 if 'timeout=' in source_code else 0.0
    vec.append(has_timeout)
    
    # "has_logging"
    has_logging = 1.0 if 'logging.' in source_code or 'logger.' in source_code else 0.0
    vec.append(has_logging)
    
    # "import_count"
    vec.append(comp["import_count"])
    
    # "has_forbidden_imports"
    vec.append(_has_forbidden_imports(source_code, list(FORBIDDEN_IMPORTS)))
    
    # "is_malformed"
    vec.append(comp["is_malformed"])

    # --- STRATEGY FEATURES ---
    strategy = candidate.get("strategy", "")
    vec.append(1.0 if 'rule' in strategy else 0.0)
    vec.append(1.0 if 'retrieval' in strategy else 0.0)
    vec.append(1.0 if 'structural' in strategy else 0.0)
    vec.append(1.0 if 'mutation' in strategy else 0.0)
    vec.append(1.0 if 'bred' in strategy else 0.0)

    # --- RULE COMPLIANCE FEATURES ---
    vec.append(float(candidate.get("applicable_active_rules_count", -1.0)) if candidate.get("applicable_active_rules_count") is not None else -1.0)
    vec.append(float(candidate.get("rule_compliance_score", -1.0)) if candidate.get("rule_compliance_score") is not None else -1.0)
    vec.append(float(candidate.get("top_rule_confidence", -1.0)) if candidate.get("top_rule_confidence") is not None else -1.0)
    vec.append(float(candidate.get("any_security_rule_violated", -1.0)) if candidate.get("any_security_rule_violated") is not None else -1.0)

    # --- HISTORICAL TOOL FEATURES ---
    tool_name = run_context.get("tool_name", "")
    tool_features = _tool_history_features(tool_name, db_path)
    
    vec.append(tool_features.get("tool_historical_fix_success_rate", -1.0))
    vec.append(tool_features.get("tool_active_failure_pattern_count", -1.0))
    
    for i in range(7):
        vec.append(tool_features.get(f"tool_dominant_root_cause_{i}", -1.0))
        
    vec.append(tool_features.get("tool_prior_similar_fix_count", -1.0))
    vec.append(tool_features.get("tool_population_avg_score", -1.0))
    vec.append(tool_features.get("tool_evolution_runs_count", -1.0))
    vec.append(tool_features.get("tool_breeding_ever_won", -1.0))

    # --- CYCLE CONTEXT FEATURES ---
    vec.append(float(run_context.get("trigger_is_hypothesis", -1.0)) if run_context.get("trigger_is_hypothesis") is not None else -1.0)
    vec.append(float(run_context.get("hypothesis_confidence", 0.5)) if run_context.get("hypothesis_confidence") is not None else 0.5)
    vec.append(float(run_context.get("failure_pattern_occurrence_count", -1.0)) if run_context.get("failure_pattern_occurrence_count") is not None else -1.0)
    vec.append(float(run_context.get("failure_memory_score", -1.0)) if run_context.get("failure_memory_score") is not None else -1.0)

    feature_vector_hash = hashlib.sha256(str(vec).encode('utf-8')).hexdigest()
    
    return vec, feature_vector_hash

# --- FAILURE PREDICTION FEATURES ---
FAILURE_FEATURES = [
    "tool_active_failure_patterns",
    "tool_dominant_category_encoded_0",
    "tool_dominant_category_encoded_1",
    "tool_dominant_category_encoded_2",
    "tool_dominant_category_encoded_3",
    "tool_dominant_category_encoded_4",
    "tool_dominant_category_encoded_5",
    "tool_dominant_category_encoded_6",
    "tool_memory_score_avg",
    "tool_historical_cycle_success_rate",
    "tool_consecutive_failed_cycles",
    "tool_days_since_last_deployment",
    "tool_population_size",
    "trigger_is_hypothesis",
    "hypothesis_confidence",
    "hypothesis_attempt_count",
    "active_rules_for_category",
    "top_rule_confidence_for_category",
    "target_candidates",
    "breeding_eligible",
]

def compute_cycle_feature_vector(run_row: dict, db_path: str) -> list[float]:
    """
    Computes features available *before* the cycle begins.
    Used for the Failure Prediction Dataset.
    """
    vec = []
    
    tool_name = run_row.get("tool_name", "")
    cycle_timestamp = run_row.get("started_at", 0.0)
    
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    try:
        # tool_active_failure_patterns
        row = cursor.execute("SELECT COUNT(*) as cnt FROM failure_patterns WHERE tool_names LIKE '%' || ? || '%' AND status = 'active' AND first_seen <= ?", (tool_name, cycle_timestamp)).fetchone()
        vec.append(float(dict(row).get("cnt", 0)) if row else 0.0)
        
        # tool_dominant_category_encoded
        rows = cursor.execute("SELECT root_cause_category, COUNT(*) as cnt FROM failure_patterns WHERE tool_names LIKE '%' || ? || '%' AND first_seen <= ? GROUP BY root_cause_category ORDER BY cnt DESC LIMIT 1", (tool_name, cycle_timestamp)).fetchone()
        cat = dict(rows).get("root_cause_category") if rows else None
        rc_encoded = _encode_root_cause(cat)
        vec.extend(rc_encoded)
        
        # tool_memory_score_avg
        # Assuming memory_score is in some table, wait I don't see it in failure_patterns schema (only occurrence_count). Let's just fallback to occurrence_count average if memory_score is missing
        try:
            row = cursor.execute("SELECT AVG(memory_score) as avg_score FROM failure_patterns WHERE tool_names LIKE '%' || ? || '%' AND status = 'active' AND first_seen <= ?", (tool_name, cycle_timestamp)).fetchone()
            vec.append(float(dict(row).get("avg_score", -1.0)) if row and dict(row).get("avg_score") is not None else -1.0)
        except sqlite3.OperationalError:
            vec.append(-1.0)
            
        # tool_historical_cycle_success_rate
        # A cycle is successful if it has a non-null winner_candidate_id linked to deployed
        hist = cursor.execute(
            '''
            SELECT er.winner_candidate_id, ih.result 
            FROM evolution_runs er 
            LEFT JOIN evolution_candidates ec ON er.winner_candidate_id = ec.id 
            LEFT JOIN improvement_history ih ON ec.improvement_history_id = ih.id 
            WHERE er.tool_name = ? AND er.started_at < ? AND er.run_status = 'completed'
            ORDER BY er.started_at ASC
            ''', (tool_name, cycle_timestamp)
        ).fetchall()
        
        total_hist = len(hist)
        if total_hist > 0:
            successes = sum(1 for r in hist if dict(r).get('result') == 'deployed')
            vec.append(successes / total_hist)
        else:
            vec.append(0.0)
            
        # tool_consecutive_failed_cycles
        consecutive_failures = 0
        for r in reversed(hist): # Ordered ASC, so reversed is DESC
            if dict(r).get('result') == 'deployed':
                break
            consecutive_failures += 1
        vec.append(float(consecutive_failures))
        
        # tool_days_since_last_deployment
        # fetch last deployment timestamp
        last_dep = cursor.execute(
            '''
            SELECT er.started_at 
            FROM evolution_runs er 
            LEFT JOIN evolution_candidates ec ON er.winner_candidate_id = ec.id 
            LEFT JOIN improvement_history ih ON ec.improvement_history_id = ih.id 
            WHERE er.tool_name = ? AND er.started_at < ? AND ih.result = 'deployed'
            ORDER BY er.started_at DESC LIMIT 1
            ''', (tool_name, cycle_timestamp)
        ).fetchone()
        if last_dep and dict(last_dep).get('started_at'):
            try:
                c_ts = float(cycle_timestamp)
                l_ts = float(dict(last_dep).get('started_at'))
                days = (c_ts - l_ts) / 86400.0
                vec.append(float(days))
            except Exception:
                vec.append(-1.0)
        else:
            vec.append(-1.0)
            
        # tool_population_size
        try:
            row = cursor.execute("SELECT COUNT(*) as cnt FROM evolution_population WHERE tool_name = ? AND added_at <= ?", (tool_name, cycle_timestamp)).fetchone()
            vec.append(float(dict(row).get("cnt", 0)) if row else 0.0)
        except sqlite3.OperationalError:
            vec.append(-1.0)
        
        # trigger_is_hypothesis
        hypothesis_id = run_row.get('hypothesis_id')
        vec.append(1.0 if hypothesis_id else 0.0)
        
        # hypothesis_confidence & attempt_count
        if hypothesis_id:
            try:
                h_row = cursor.execute("SELECT confidence, attempt_count FROM hypotheses WHERE id = ?", (hypothesis_id,)).fetchone()
                if h_row:
                    h_dict = dict(h_row)
                    vec.append(float(h_dict.get('confidence', 0.5)))
                    vec.append(float(h_dict.get('attempt_count', 0)))
                else:
                    vec.extend([0.5, 0.0])
            except sqlite3.OperationalError:
                vec.extend([0.5, 0.0])
        else:
            vec.extend([0.5, 0.0])
            
        # active_rules_for_category & top_rule_confidence_for_category
        # Use run_row root_cause_category or fallback to dominant cat
        rc_cat = run_row.get("root_cause_category") or cat
        if rc_cat:
            try:
                r_rows = cursor.execute("SELECT confidence FROM engineering_rules WHERE target_category = ? AND status = 'active'", (rc_cat,)).fetchall()
                vec.append(float(len(r_rows)))
                top_conf = max([float(dict(r).get('confidence', 0.0)) for r in r_rows]) if r_rows else 0.0
                vec.append(top_conf)
            except sqlite3.OperationalError:
                vec.extend([0.0, 0.0])
        else:
            vec.extend([0.0, 0.0])
            
    except sqlite3.OperationalError as e:
        # Fallback if remaining table joins fail
        while len(vec) < 18:
            vec.append(-1.0)
            
    conn.close()
    
    # Pad if we caught error early
    while len(vec) < 18:
        vec.append(-1.0)
    
    # target_candidates
    try:
        from aria.config import settings
        target_candidates = getattr(settings, "EVOLUTION_CANDIDATES_PER_CYCLE", 5)
    except ImportError:
        target_candidates = 5
    vec.append(float(target_candidates))
    
    # breeding_eligible
    population_size = vec[12] if len(vec) > 12 else 0
    vec.append(1.0 if population_size >= 2 else 0.0)
    
    return vec

# --- RISK PREDICTION FEATURES ---
RISK_FEATURES = [
    "source_lines_of_code",
    "cyclomatic_complexity",
    "has_retry_logic",
    "exception_scope_width",
    "rule_compliance_score",
    "composite_score",
    "rank_1_margin",
    "strategy_is_rule_guided",
    "strategy_is_retrieval_based",
    "strategy_is_structural",
    "strategy_is_mutation",
    "strategy_is_bred",
    "tool_prior_rollback_rate",
    "tool_failure_pattern_count",
    "trigger_is_hypothesis",
    "hypothesis_confidence",
    "any_security_rule_violated",
    "applicable_rules_count",
]

def compute_risk_feature_vector(candidate_row: dict, db_path: str) -> list[float]:
    """
    Computes features for post-deployment risk prediction.
    """
    vec = []
    source_code = candidate_row.get("source_code", "")
    if source_code is None:
        source_code = ""
        
    comp = _source_complexity(source_code)
    
    vec.append(comp["lines"])
    vec.append(comp["complexity"])
    
    has_retry = 1.0 if re.search(r'retry|backoff|attempt', source_code, re.IGNORECASE) else 0.0
    vec.append(has_retry)
    
    vec.append(_exception_scope_width(source_code))
    vec.append(float(candidate_row.get("rule_compliance_score", -1.0)) if candidate_row.get("rule_compliance_score") is not None else -1.0)
    vec.append(float(candidate_row.get("composite_score", -1.0)) if candidate_row.get("composite_score") is not None else -1.0)
    vec.append(float(candidate_row.get("rank_1_margin", 0.0)) if candidate_row.get("rank_1_margin") is not None else 0.0)
    
    strategy = candidate_row.get("strategy", "")
    if strategy is None: strategy = ""
    vec.append(1.0 if 'rule' in strategy else 0.0)
    vec.append(1.0 if 'retrieval' in strategy else 0.0)
    vec.append(1.0 if 'structural' in strategy else 0.0)
    vec.append(1.0 if 'mutation' in strategy else 0.0)
    vec.append(1.0 if 'bred' in strategy else 0.0)
    
    # tool_prior_rollback_rate and tool_failure_pattern_count at deploy time
    tool_name = candidate_row.get("tool_name", "")
    deploy_time = candidate_row.get("ih_timestamp", 0.0) # From improvement_history
    
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    try:
        # tool_prior_rollback_rate
        hist = cursor.execute(
            '''
            SELECT result 
            FROM improvement_history 
            WHERE tool_name = ? AND timestamp < ? AND result IN ('deployed', 'rolled_back')
            ''', (tool_name, deploy_time)
        ).fetchall()
        
        if hist:
            rollbacks = sum(1 for r in hist if dict(r).get('result') == 'rolled_back')
            vec.append(rollbacks / len(hist))
        else:
            vec.append(0.0)
            
        # tool_failure_pattern_count (active at deploy time)
        row = cursor.execute("SELECT COUNT(*) as cnt FROM failure_patterns WHERE tool_names LIKE '%' || ? || '%' AND status = 'active' AND first_seen <= ?", (tool_name, deploy_time)).fetchone()
        vec.append(float(dict(row).get("cnt", 0)) if row else 0.0)
        
    except sqlite3.OperationalError:
        vec.extend([-1.0, -1.0])
        
    conn.close()
    
    hyp_trigger = candidate_row.get("trigger_is_hypothesis", 0.0)
    vec.append(float(hyp_trigger) if hyp_trigger is not None else 0.0)
    
    hyp_conf = candidate_row.get("hypothesis_confidence", 0.5)
    vec.append(float(hyp_conf) if hyp_conf is not None else 0.5)
    
    sec_rule = candidate_row.get("any_security_rule_violated", -1.0)
    vec.append(float(sec_rule) if sec_rule is not None else -1.0)
    
    app_rules = candidate_row.get("applicable_rules_count")
    if app_rules is None:
        app_rules = candidate_row.get("applicable_active_rules_count", -1.0)
    vec.append(float(app_rules) if app_rules is not None else -1.0)
    
    return vec


